import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { AnalysisReport, isSectionError } from '../types/analysis.types';

@Injectable()
export class PdfGeneratorService {
  generate(report: AnalysisReport): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(22).text('WebPulses AI', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).text(`URL: ${report.url}`);
      doc.text(`Analyzed: ${new Date(report.analyzedAt).toLocaleString()}`);
      doc.text(`Overall Grade: ${report.summary.grade}`);
      doc.moveDown();
      doc.fontSize(14).text('Summary');
      doc.fontSize(11).text(report.summary.overview);
      doc.moveDown();
      report.summary.recommendations.forEach((r, i) => {
        doc.text(`${i + 1}. [${r.priority}] ${r.message}`);
      });

      this.section(doc, 'SEO', () => {
        if (isSectionError(report.seo)) return doc.text(report.seo.error);
        doc.text(`Score: ${report.seo.score}`);
        report.seo.issues.forEach((i) => doc.text(`- ${i.message}`));
      });

      this.section(doc, 'Speed', () => {
        if (isSectionError(report.speed)) return doc.text(report.speed.error);
        doc.text(`Performance: ${report.speed.performanceScore}`);
        doc.text(`LCP: ${report.speed.lcp.value} | CLS: ${report.speed.cls.value} | INP: ${report.speed.inp.value}`);
      });

      this.section(doc, 'Security', () => {
        if (isSectionError(report.security)) return doc.text(report.security.error);
        doc.text(`Score: ${report.security.score}`);
        report.security.headers.forEach((h) => doc.text(`${h.name}: ${h.status}`));
      });

      this.section(doc, 'Tech Stack', () => {
        if (isSectionError(report.techStack)) return doc.text(report.techStack.error);
        report.techStack.technologies.forEach((t) => doc.text(`${t.name} (${t.category})`));
      });

      const pages = doc.bufferedPageRange();
      for (let i = pages.start; i < pages.start + pages.count; i++) {
        doc.switchToPage(i);
        doc.fontSize(8).text(`Generated by WebPulses AI — Page ${i - pages.start + 1}`, 50, doc.page.height - 40, { align: 'center' });
      }

      doc.end();
    });
  }

  private section(doc: PDFKit.PDFDocument, title: string, body: () => void) {
    doc.addPage();
    doc.fontSize(16).text(title);
    doc.moveDown(0.5);
    doc.fontSize(11);
    body();
  }
}
